prefix-private: "&c&lᴄᴀssᴀ &f&lᴘʀɪᴠᴀᴛᴀ &7>>&r "

private-chest:
  noPermission: "&cɴᴏɴ ʜᴀɪ ɪʟ ᴘᴇʀᴍᴇssᴏ ᴅɪ ᴀᴘʀɪʀᴇ ᴏ̨ᴜᴇsᴛᴀ ᴄʜᴇsᴛ ᴘʀɪᴠᴀᴛᴀ!"
  enoughPlayers: "&cᴘᴜᴏɪ ɪɴsᴇʀɪʀᴇ ᴀʟᴛʀɪ 2 ɴᴏᴍɪ ᴅɪ ɢɪᴏᴄᴀᴛᴏʀɪ ᴅᴏᴘᴏ ɪʟ ᴛᴜᴏ ɴᴏᴍᴇ!"
  success: "&aʜᴀɪ ᴄʀᴇᴀᴛᴏ ᴄᴏʀʀᴇᴛᴛᴀᴍᴇɴᴛᴇ ɪʟ ᴛᴜᴏ ʙᴀᴜʟᴇ ᴘʀɪᴠᴀᴛᴏ! sᴇ ᴠᴜᴏɪ ᴘʀᴏᴛᴇɢɢᴇʀᴇ ᴜɴᴀ ᴅᴏᴘᴘɪᴀ ᴄʜᴇsᴛ ᴅᴇᴠɪ ᴍᴇᴛᴛᴇʀᴇ ɪʟ ᴄᴀʀᴛᴇʟʟᴏ ᴀɴᴄʜᴇ sᴜ ʟ'ᴀʟᴛʀᴀ ᴘᴀʀᴛᴇ!"
  break: "&cɴᴏɴ ᴘᴜᴏɪ ʀᴏᴍᴘᴇʀʟᴏ!"
  update: "&cᴄᴀʀᴛᴇʟʟᴏ ᴀɢɢɪᴏʀɴᴀᴛᴏ!"
  cannotChange: '&cɴᴏɴ ᴘᴜᴏɪ ᴄᴀᴍʙɪᴀʀᴇ ɪʟ ᴘʀᴏᴘʀɪᴇᴛᴀʀɪᴏ ᴏ ɪʟ ᴛɪᴘᴏ ᴅᴇʟ ʙᴀᴜʟᴇ ᴘʀɪᴠᴀᴛᴏ, ʀᴏᴍᴘɪ ɪʟ ᴄᴀʀᴛᴇʟʟᴏ ᴘᴇʀ ᴄᴀᴍʙɪᴀʀʟᴏ.'